// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATD_9pKsbA7eiMfpTwkS2fiAYc9_8Qg80',
    appId: '1:869229930083:web:4641b57d8b199b1611fa56',
    messagingSenderId: '869229930083',
    projectId: 'bdcrudmascotas',
    authDomain: 'bdcrudmascotas.firebaseapp.com',
    storageBucket: 'bdcrudmascotas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_sBBURm1zSWb2aL6XsogXjUm984L6mo',
    appId: '1:869229930083:android:30c5efcb305af7ef11fa56',
    messagingSenderId: '869229930083',
    projectId: 'bdcrudmascotas',
    storageBucket: 'bdcrudmascotas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzIwL4FkZ20qEPSGRz8u-jcj38vGLSoHE',
    appId: '1:869229930083:ios:633c75fc870936b011fa56',
    messagingSenderId: '869229930083',
    projectId: 'bdcrudmascotas',
    storageBucket: 'bdcrudmascotas.firebasestorage.app',
    iosBundleId: 'com.tuusuario.veterinaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzIwL4FkZ20qEPSGRz8u-jcj38vGLSoHE',
    appId: '1:869229930083:ios:633c75fc870936b011fa56',
    messagingSenderId: '869229930083',
    projectId: 'bdcrudmascotas',
    storageBucket: 'bdcrudmascotas.firebasestorage.app',
    iosBundleId: 'com.tuusuario.veterinaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATD_9pKsbA7eiMfpTwkS2fiAYc9_8Qg80',
    appId: '1:869229930083:web:f541938848ab09b911fa56',
    messagingSenderId: '869229930083',
    projectId: 'bdcrudmascotas',
    authDomain: 'bdcrudmascotas.firebaseapp.com',
    storageBucket: 'bdcrudmascotas.firebasestorage.app',
  );
}
